
-- create
CREATE TABLE cadFun (
  CODEFUN INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(40) NOT NULL,
  DEPTO CHAR(2),
  FUNCAO CHAR(20),
  SALARIO NUMERIC (10,2),
  FILHOS INT
);

-- insert
INSERT INTO cadFun VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00, 0);
INSERT INTO cadFun VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 1985.75, 2);
INSERT INTO cadFun VALUES (7, 'APARECIDA SILVA', '3', 'SECRETARIA', 1200.50, 1);
INSERT INTO cadFun VALUES (9, 'SOLANGE PACHECO', '5', 'SUPERVISORA', 1599.51, 3);
INSERT INTO cadFun VALUES (6, 'MARCELO SOUZA', '3', 'ANALISTA', 2250.11, 2);
INSERT INTO cadFun VALUES (1, 'CELIO NASCIMENTO', '2', 'SECRETARIA', 1200.50, 1);
INSERT INTO cadFun VALUES (2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00, 0);
INSERT INTO cadFun VALUES (5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00, 0);
INSERT INTO cadFun VALUES (4, 'CARLOS BASTOS', '5', 'VENDEDOR', 1530.00, 1);
INSERT INTO cadFun VALUES (25, 'PEDRO SILVA', '3', 'SUPERVISOR', 1599.51, 2);
INSERT INTO cadFun VALUES (3, 'ANA BASTOS', '5', 'VENDEDORA', 1530.00, 3);
INSERT INTO cadFun VALUES (10, 'PAULO DA SILVA', '2', 'VENDEDOR', 1530.00, 4);

-- fetch 

SELECT * from cadFun;

-- Exercício 7
SELECT codefun, nome, SALARIO + 250 FROM cadFun;

-- Exercício 8
SELECT * FROM cadFun WHERE FUNCAO = 'ANALISTA'; 

-- Exercício 9
SELECT * FROM cadFun WHERE SALARIO > 1700;

-- Exercício 10
SELECT * FROM cadFun WHERE SALARIO < 1700;

-- Exercício 11
SELECT * FROM cadFun WHERE SALARIO = 1700;

-- Exercício 12
SELECT * FROM cadFun WHERE FUNCAO = 'ANALISTA' AND FUNCAO = 'PROGRAMADOR';

-- Exercício 13
SELECT * FROM cadFun WHERE FUNCAO = 'ANALISTA' OR FUNCAO = 'PROGRAMADOR' AND SALARIO > 1200;

-- Exercício 14
SELECT * FROM cadFun WHERE FUNCAO != 'ANALISTA' AND FUNCAO != 'PROGRAMADOR';


-- Exercício 15
SELECT * FROM cadFun WHERE FUNCAO = 'ANALISTA' AND FUNCAO = 'PROGRAMADOR';
