-- COMANDOS PARA CRIAR TABELAS

CREATE TABLE FUNCIONARIOS (
	id_funcionario SERIAL NOT NULL PRIMARY KEY,
	nome_funcionario VARCHAR(100) NOT NULL,
	status_funcionario BOOLEAN NOT NULL,
	cidade_funcionario VARCHAR(50) 
);

CREATE TABLE PRODUTOS (
	id_produtos INT NOT NULL PRIMARY KEY,
	nome_produtos varchar(255) NOT NULL,
	qtde_produtos INT NOT NULL,
	valor_produtos MONEY NOT NULL,
	validade_produtos date NOT NULL
	FOREIGN KEY id_funcionarios REFERENCES FUNCIONARIOS -- Chave estrangeira
);

-- COMANDOS PARA VISUALIZAR RESULTADOS

SELECT * FROM FUNCIONARIOS;

-- COMANDO PARA ADICIONAR COLUNA NA TABELA

ALTER TABLE funcionarios ADD sexo CHAR(1);

-- COMANDO PARA EXCLUIR COLUNA NA TABLE

ALTER TABLE funcionarios DROP COLUMN sexo;

-- COMANDO PARA RENOMEAR O NOME DA COLUNA

ALTER TABlE FUNCIONARIOS RENAME COLUMN cidade_funcionario TO city;

-- COMANDO PARA EXCLUIR CHAVE PRIMÁRIA/ESTRANGEIRA DO BANCO

ALTER TABLE funcionarios DROP PRIMARY KEY; --FOREI